CREATE USER  youtube IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

--ROLES
GRANT "CONNECT" TO youtube;
GRANT CREATE TABLE TO youtube;
GRANT ALL PRIVILEGES TO youtube;
SELECT * FROM system_privilege_map; -- Podemos obtener la lista de permisos del sistema
SELECT * FROM USER_SYS_PRIVS;  -- ver privilegios
--PRIVILEGIOS

GRANT ALTER TABLESPACE TO youtube;
GRANT EXECUTE ANY PROCEDURE TO youtube;
-- tablas
CREATE TABLE DIRECCION (
IDDERECCION NCHAR(7)NOT NULL CONSTRAINT PK_IDDERECCION PRIMARY KEY,
DISTRITO NVARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(50)NOT NULL);

CREATE TABLE PERSONA(
DNI CHAR(10)PRIMARY KEY,
MNOMBRE VARCHAR2(50) NOT NULL,
PATERNO VARCHAR2(50)NOT NULL,
MATERNO VARCHAR2(50)NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
SEXO CHAR(1) CONSTRAINT CH_SEXO CHECK (SEXO IN ('M','F'))
);
-- RESTRICCIONES DE TABLAS
CREATE TABLE CARGO (
ID_CARGO CHAR (7),
CARGO VARCHAR2(30)NOT NULL PRIMARY KEY,
--
SUELDO NUMBER (8,2) CONSTRAINT CH_SUELDO CHECK(SUELDO BETWEEN 100.00 AND 4000.40)
);

CREATE TABLE TELEFONO (
ID_TELEFONO CHAR(7),
DNI CHAR(10),
TELEFONO CHAR(10) NOT NULL,
CONSTRAINT PK_TELEFONO PRIMARY KEY(ID_TELEFONO,DNI)
);
DESCRIBE TELEFONO;
DESC TELEFONO;
SELECT * FROM TELEFONO;
ALTER TABLE TELEFONO ADD MARCA VARCHAR (20);
ALTER TABLE TELEFONO MODIFY (MARCA NOT NULL); 

DESCRIBE TELEFONO;

ALTER TABLE TELEFONO
DROP COLUMN MARCA;

ALTER TABLE TELEFONO MODIFY MARCA VARCHAR(30) DEFAULT 'ENTEL';

CREATE TABLE CLIENTE(
DNI VARCHAR (10)PRIMARY KEY,
FECHA_REGISTRO DATE NULL,
FOREIGN KEY (DNI) 
REFERENCES PERSONA (DNI)
);
DESCRIBE PERSONA;
DROP TABLE PERSONA;

CREATE TABLE TELEFONO (
DNI CHAR(10)PRIMARY KEY,
ID_TELEFONO CHAR(7),
TELEFONO CHAR(10) NOT NULL);


CREATE TABLE PERSONA(
DNI CHAR(10)PRIMARY KEY,
MNOMBRE VARCHAR2(50) NOT NULL,
PATERNO VARCHAR2(50)NOT NULL,
MATERNO VARCHAR2(50)NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
SEXO CHAR(1) CONSTRAINT CH_SEXO CHECK (SEXO IN ('M','F'))
);

CREATE TABLE CLIENTE(
DNI CHAR(10)PRIMARY KEY,
FECHA_REGISTRO DATE NULL,
FOREIGN KEY (DNI) REFERENCES PERSONA(DNI)
);

CREATE TABLE PEPE (NOMBRE VARCHAR(10));

SELECT * FROM CLIENTE; 
DESC CLIENTE;


ALTER TABLE PERSONA 
ADD CONSTRAINT FK_DIRECCION FOREIGN KEY (DIRECCION)
REFERENCES DIRECCION (IDDERECCION);

DESC DIRECCION;
DESC PERSONA;

ALTER TABLE PERSONA 
ADD CONSTRAINT PK_IDDERECCION FOREIGN KEY
(DIRECCION) REFERENCES DIRECCION (IDDERECCION);

CREATE TABLE EMPLEADO (
ID_EMPLEADO NCHAR(7),
DNI CHAR(10),
HORAS_TRABAJO NUMBER,

);




